# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "cincybikemap.xcodeproj")
    build_app(workspace: "cincybikemap.xcworkspace", scheme: "cincybikemap")
    upload_to_app_store
  end
end

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'GitHub actions release'
  lane :version do |options|
    updateVersion(options)
    increment_build_number(xcodeproj: 'cincybikemap.xcodeproj')
  end
  
  lane :github do |_options|
    build_number = number_of_commits(all: true)
      increment_build_number(build_number: build_number, xcodeproj: 'cincybikemap.xcodeproj')
    create_keychain(
      name: 'ios_app_keychain',
      password: 'password',
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
    import_certificate(
      certificate_path: 'distribution.p12',
      certificate_password: ENV['CERT_PASSWORD'],
      keychain_name: 'ios_app_keychain',
      keychain_password: 'password'
    )
    install_provisioning_profile(path: 'Distro.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'cincybikemap.xcodeproj',
      target_filter: 'cincybikemap',
      profile: 'Distro.mobileprovision',
      build_configuration: 'Release',
      code_signing_identity: 'Apple Distribution'
    )
    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['API_KEY_ISSUER_ID'],
      key_filepath: 'app_store_key.p8'
    )
  
    build_app(
      workspace: 'cincybikemap.xcworkspace',
      scheme: 'cincybikemap',
      codesigning_identity: 'Apple Distribution: Vince Internet Company Enterprises LLC',
      include_bitcode: true,
      include_symbols: true,
    )

    upload_to_app_store(
      force: true,
      reject_if_possible: false,
      skip_metadata: true,
      skip_screenshots: true,
      languages: ['en-US'],
      release_notes: {
        'default' => 'Bug fixes',
        'en-US' => 'bug fixed'
      },
      submit_for_review: false,
      precheck_include_in_app_purchases: false,
      automatic_release: false,
      submission_information: {
        add_id_info_uses_idfa: false,
        add_id_info_serves_ads: false,
        add_id_info_tracks_install: true,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: true,
        export_compliance_encryption_updated: false
      },
      api_key: api_key
    )
  end  
end


